apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: app1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "256Mi"
              cpu: "256m"
            limits:
              memory: "256Mi"
              cpu: "256m"
          volumeMounts:
          - name: sharedDir
            mountPath: /usr/share/nginx/html/
      initContainers:
        - name: init-app1
          image: busybox:1.28
          command:
            [
              "sh",
              "-c",
              "echo '<html><head><title>app1</title></head><body><h1>Welcome to app1!</h1></body></html>' > /usr/share/nginx/html/index.html",
            ]
          resources:
            requests:
              memory: "256Mi"
              cpu: "256m"
            limits:
              memory: "256Mi"
              cpu: "256m"
          volumeMounts:
          - name: sharedDir
            mountPath: /usr/share/nginx/html/
      volumes:
      - name: sharedDir
        emptyDir: {}