apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prod
  namespace: argocd
spec:
  generators:
    - git:
        directories:
          - path: apps/*
        repoURL: https://github.com/elouazzany/gitops-repo
        revision: main
  template:
    metadata:
      name: 'prod-{{path.basename}}'
    spec:
      destination:
        namespace: prod
        server: https://kubernetes.default.svc
      project: default
      source:
        path: '{{path}}/overlays/prod'
        repoURL: https://github.com/elouazzany/gitops-repo
        targetRevision: main
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
