apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: staging
  namespace: argocd
spec:
  generators:
    - git:
        directories:
          - path: apps/*
        repoURL: https://github.com/elouazzany/gitops-repo
        revision: main
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      destination:
        namespace: staging
        server: https://kubernetes.default.svc
      project: default
      source:
        path: '{{path}}//overlays/staging'
        repoURL: https://github.com/elouazzany/gitops-repo
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
